### PR TITLE
Open the comments instead of both link and comments

### PR DESCRIPTION
**Pull request by edcaron**

### CODE REVIEW

**Comment by nickrussler** [comment]
Thank you for your contribution. My problem with the PR right now is that it changes the `Open comments` to an `Open only comments` option. I think the best way is to add three radio buttons for the `Open comments` Option with `Don't open comments`, `Open comments and articles` and `Open only comments` as options. This would also require to migrate existing configuration to the new option values.

**Comment by edcaron** [comment]
I also thought it would be better that way. I gonna try doing it.

**Comment by edcaron** [comment]
Done.

**Comment by nickrussler** [comment]
Great! I will review your code, as soon as possible.

**Pull request closed without merging**
